import pandas
import matplotlib.pyplot as plt
#import plotly.express as px
import seaborn as sns
import numpy as np


base_perf_svm = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_FS_SVM_10.csv")
aug_perf_svm = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_FS_SVM_10.csv")
base_perf_icare_10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_icare10_10.csv")
aug_perf_icare_10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_icare10_10.csv")
base_perf_icare_100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_icare100_10.csv")
aug_perf_icare_100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_icare100_10.csv")
base_perf_cox = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_cox_10.csv")
aug_perf_cox = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_cox_10.csv")
base_perf_rsf10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_rsf10_10.csv")
aug_perf_rsf10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_rsf10_10.csv")
base_perf_rsf100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_rsf100_10.csv")
aug_perf_rsf100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_rsf100_10.csv")
base_perf_gb10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_gb10_10.csv")
aug_perf_gb10 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_gb10_10.csv")
base_perf_gb100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_base_gb100_10.csv")
aug_perf_gb100 = pandas.read_csv("../csvs/Performance/Perf_Hecktor_augmented_gb100_10.csv")



#sns.lineplot(base_perf_svm,x="nb_variables", y="CI_train", color=(1, 0, 0, .2), dashes=(2,2), legend="brief", label="Train CI (SVM, Base)")
#sns.lineplot(aug_perf_svm,x="nb_variables", y="CI_train", color=(1, 0, 0, .2), legend="brief", label="Train CI (SVM, Augmented)")
#sns.lineplot(base_perf_icare_10,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), dashes=(2,2), legend="brief", label="Train CI (Icare, Base)")
#sns.lineplot(aug_perf_icare_10,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), legend="brief", label="Train CI (Icare, Augmented)")
#sns.lineplot(base_perf_icare_100,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), dashes=(2,2), legend="brief", label="Train CI (Icare, Base)")
#sns.lineplot(aug_perf_icare_100,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), legend="brief", label="Train CI (Icare, Augmented)")
#sns.lineplot(base_perf_cox,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Train CI (CoxNet, Base)")
#sns.lineplot(aug_perf_cox,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), legend="brief", label="Train CI (CoxNet, Augmented)")
#sns.lineplot(base_perf_rsf10,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), legend="brief", label="Train CI (RSF_10, Base)")
#sns.lineplot(aug_perf_rsf10,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Train CI (RSF_10, Augmented)")
#sns.lineplot(base_perf_rsf100,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), legend="brief", label="Train CI (RSF_100, Base)")
#sns.lineplot(aug_perf_rsf100,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Train CI (RSF_100, Augmented)")
#sns.lineplot(base_perf_gb10,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), legend="brief", label="Train CI (GB_10, Base)")
#sns.lineplot(aug_perf_gb10,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Train CI (GB_10, Augmented)")

sns.lineplot(base_perf_svm,x="nb_variables", y="CI_test", color=(1, 0, 0, .2), dashes=(2,2), legend="brief", label="Test CI (SVM, Base)")
sns.lineplot(aug_perf_svm,x="nb_variables", y="CI_test", color=(1, 0, 0, .2), legend="brief", label="Test CI (SVM, Augmented)")
sns.lineplot(base_perf_icare_10,x="nb_variables", y="CI_test", color=(0, 0, 1, .2), dashes=(2,2), legend="brief", label="Test CI (Icare, Base)")
sns.lineplot(aug_perf_icare_10,x="nb_variables", y="CI_test", color=(0, 0, 1, .2), legend="brief", label="Test CI (Icare_10, Augmented)")
sns.lineplot(base_perf_icare_100,x="nb_variables", y="CI_test", color=(1, 0, 1, .2), dashes=(2,2), legend="brief", label="Test CI (Icare, Base)")
sns.lineplot(aug_perf_icare_100,x="nb_variables", y="CI_test", color=(1, 0, 1, .2), legend="brief", label="Test CI (Icare_100, Augmented)")
sns.lineplot(base_perf_cox,x="nb_variables", y="CI_test", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Test CI (CoxNet, Base)")
sns.lineplot(aug_perf_cox,x="nb_variables", y="CI_test", color=(0, 1, 0, .2), legend="brief", label="Test CI (CoxNet, Augmented)")
sns.lineplot(base_perf_rsf10,x="nb_variables", y="CI_test", color=(0, 1, 1, .2), dashes=(2,2), legend="brief", label="Test CI (RSF_10, Base)")
sns.lineplot(aug_perf_rsf10,x="nb_variables", y="CI_test", color=(0, 1, 1, .2), legend="brief", label="Test CI (RSF_10, Augmented)")
sns.lineplot(base_perf_rsf100,x="nb_variables", y="CI_test", color=(0, .5, 1, .2), dashes=(2,2), legend="brief", label="Test CI (RSF_100, Base)")
sns.lineplot(aug_perf_rsf100,x="nb_variables", y="CI_test", color=(0, .5, 1, .2), legend="brief", label="Test CI (RSF_100, Augmented)")
sns.lineplot(base_perf_gb10,x="nb_variables", y="CI_test", color=(1, .5, 0, .2), dashes=(2,2), legend="brief", label="Test CI (GB_10, Base)")
sns.lineplot(aug_perf_gb10,x="nb_variables", y="CI_test", color=(1, .5, 0, .2), legend="brief", label="Test CI (GB_10, Augmented)")
sns.lineplot(base_perf_gb100,x="nb_variables", y="CI_test", color=(.4, .4, 0, .2), dashes=(2,2), legend="brief", label="Test CI (GB_100, Base)")
sns.lineplot(aug_perf_gb100,x="nb_variables", y="CI_test", color=(.4, .4, 0, .2), legend="brief", label="Test CI (GB_100, Augmented)")

coords_base_cox = (np.argmax(base_perf_cox["CI_train"])+1, base_perf_cox["CI_test"][np.argmax(base_perf_cox["CI_train"])])
coords_aug_cox = (np.argmax(aug_perf_cox["CI_train"])+1, aug_perf_cox["CI_test"][np.argmax(aug_perf_cox["CI_train"])])
coords_base_svm = (np.argmax(base_perf_svm["CI_train"])+1, base_perf_svm["CI_test"][np.argmax(base_perf_svm["CI_train"])])
coords_aug_svm = (np.argmax(aug_perf_svm["CI_train"])+1, aug_perf_svm["CI_test"][np.argmax(aug_perf_svm["CI_train"])])
coords_base_icare_10 = (np.argmax(base_perf_icare_10["CI_train"])+1, base_perf_icare_10["CI_test"][np.argmax(base_perf_icare_10["CI_train"])])
coords_aug_icare_10 = (np.argmax(aug_perf_icare_10["CI_train"])+1, aug_perf_icare_10["CI_test"][np.argmax(aug_perf_icare_10["CI_train"])])
coords_base_icare_100 = (np.argmax(base_perf_icare_100["CI_train"])+1, base_perf_icare_100["CI_test"][np.argmax(base_perf_icare_100["CI_train"])])
coords_aug_icare_100 = (np.argmax(aug_perf_icare_100["CI_train"])+1, aug_perf_icare_100["CI_test"][np.argmax(aug_perf_icare_100["CI_train"])])
coords_base_rsf_10 = (np.argmax(base_perf_rsf10["CI_train"])+1, base_perf_rsf10["CI_test"][np.argmax(base_perf_rsf10["CI_train"])])
coords_aug_rsf_10 = (np.argmax(aug_perf_rsf10["CI_train"])+1, aug_perf_rsf10["CI_test"][np.argmax(aug_perf_rsf10["CI_train"])])
coords_base_rsf_100 = (np.argmax(base_perf_rsf100["CI_train"])+1, base_perf_rsf100["CI_test"][np.argmax(base_perf_rsf100["CI_train"])])
coords_aug_rsf_100 = (np.argmax(aug_perf_rsf100["CI_train"])+1, aug_perf_rsf100["CI_test"][np.argmax(aug_perf_rsf100["CI_train"])])
coords_base_gb_10 = (np.argmax(base_perf_gb10["CI_train"])+1, base_perf_gb10["CI_test"][np.argmax(base_perf_gb10["CI_train"])])
coords_aug_gb_10 = (np.argmax(aug_perf_gb10["CI_train"])+1, aug_perf_gb10["CI_test"][np.argmax(aug_perf_gb10["CI_train"])])
coords_base_gb_100 = (np.argmax(base_perf_gb100["CI_train"])+1, base_perf_gb100["CI_test"][np.argmax(base_perf_gb100["CI_train"])])
coords_aug_gb_100 = (np.argmax(aug_perf_gb100["CI_train"])+1, aug_perf_gb100["CI_test"][np.argmax(aug_perf_gb100["CI_train"])])

plt.scatter(*coords_base_cox, color=(0,1,0), marker="P")
plt.scatter(*coords_aug_cox, color=(0,1,0), marker="*")
plt.scatter(*coords_base_svm, color=(1,0,0), marker="P")
plt.scatter(*coords_aug_svm, color=(1,0,0), marker="*")
plt.scatter(*coords_base_icare_10, color=(0,0,1), marker="P")
plt.scatter(*coords_aug_icare_10, color=(0,0,1), marker="*")
plt.scatter(*coords_base_icare_100, color=(1,0,1), marker="P")
plt.scatter(*coords_aug_icare_100, color=(1,0,1), marker="*")
plt.scatter(*coords_base_rsf_10, color=(0,1,1), marker="P")
plt.scatter(*coords_aug_rsf_10, color=(0,1,1), marker="*")
plt.scatter(*coords_base_rsf_100, color=(0,.5,1), marker="P")
plt.scatter(*coords_aug_rsf_100, color=(0,.5,1), marker="*")
plt.scatter(*coords_base_gb_10, color=(1,.5,0), marker="P")
plt.scatter(*coords_aug_gb_10, color=(1,.5,0), marker="*")
plt.scatter(*coords_base_gb_100, color=(.4, .4, 0), marker="P")
plt.scatter(*coords_aug_gb_100, color=(.4, .4, 0), marker="*")

plt.annotate("", xytext=coords_base_cox, xy=coords_aug_cox,
             arrowprops=dict(arrowstyle="->", ec=(0,1,0)))
plt.annotate("", xytext=coords_base_svm, xy=coords_aug_svm,
             arrowprops=dict(arrowstyle="->", ec=(1,0,0)))
plt.annotate("", xytext=coords_base_icare_10, xy=coords_aug_icare_10,
             arrowprops=dict(arrowstyle="->", ec=(0,0,1)))
plt.annotate("", xytext=coords_base_icare_100, xy=coords_aug_icare_100,
             arrowprops=dict(arrowstyle="->", ec=(1,0,1)))
plt.annotate("", xytext=coords_base_rsf_10, xy=coords_aug_rsf_10,
             arrowprops=dict(arrowstyle="->", ec=(0,1,1)))
plt.annotate("", xytext=coords_base_rsf_100, xy=coords_aug_rsf_100,
             arrowprops=dict(arrowstyle="->", ec=(0,.5,1)))
plt.annotate("", xytext=coords_base_gb_10, xy=coords_aug_gb_10,
             arrowprops=dict(arrowstyle="->", ec=(1,.5,0)))
plt.annotate("", xytext=coords_base_gb_100, xy=coords_aug_gb_100,
             arrowprops=dict(arrowstyle="->", ec=(.4, .4, 0)))

plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")
plt.title("Concordance Index (CI) for a given number of selected features", weight='bold')
plt.tight_layout()

'''
plt.plot(base_ci_train, "b--")
plt.plot(base_ci_test, "bo-")
plt.plot(aug_ci_train, "r--")
plt.plot(aug_ci_test, "ro-")
'''
plt.show()

####
#plt.suptitle("Training and test CI values for each model", weight='bold')
plt.subplot(3,3,1)
plt.ylim(.5,.7)
plt.title("Fast Survival-SVM")
sns.lineplot(base_perf_svm,x="nb_variables", y="CI_train", color=(1, 0, 0, .2), dashes=(2,2), legend="brief", label="Train CI")
sns.lineplot(aug_perf_svm,x="nb_variables", y="CI_train", color=(1, 0, 0, .2), legend="brief", label="Train CI")
sns.lineplot(base_perf_svm,x="nb_variables", y="CI_test", color=(1, 0, 0, 1), dashes=(2,2), legend="brief", label="Test CI")
sns.lineplot(aug_perf_svm,x="nb_variables", y="CI_test", color=(1, 0, 0, 1), legend="brief", label="Test CI")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,2)
plt.ylim(.5,.7)
plt.title("Icare (10 classifiers)")
sns.lineplot(base_perf_icare_10,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), dashes=(2,2), legend="brief", label="Train CI")
sns.lineplot(aug_perf_icare_10,x="nb_variables", y="CI_train", color=(0, 0, 1, .2), legend="brief", label="Train CI")
sns.lineplot(base_perf_icare_10,x="nb_variables", y="CI_test", color=(0, 0, 1, 1), dashes=(2,2), legend="brief", label="Test CI")
sns.lineplot(aug_perf_icare_10,x="nb_variables", y="CI_test", color=(0, 0, 1, 1), legend="brief", label="Test CI")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,3)
plt.ylim(.5,.7)
plt.title("Icare (100 classifiers)")
sns.lineplot(base_perf_icare_100,x="nb_variables", y="CI_train", color=(1, 0, 1, .2), dashes=(2,2), legend="brief", label="Train CI")
sns.lineplot(aug_perf_icare_100,x="nb_variables", y="CI_train", color=(1, 0, 1, .2), legend="brief", label="Train CI")
sns.lineplot(base_perf_icare_100,x="nb_variables", y="CI_test", color=(1, 0, 1, 1), dashes=(2,2), legend="brief", label="Test CI")
sns.lineplot(aug_perf_icare_100,x="nb_variables", y="CI_test", color=(1, 0, 1, 1), legend="brief", label="Test CI")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,4)
plt.title("CoxNet Survival Analysis")
plt.ylim(.5,.7)
sns.lineplot(base_perf_cox,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), dashes=(2,2), legend="brief", label="Train CI")
sns.lineplot(aug_perf_cox,x="nb_variables", y="CI_train", color=(0, 1, 0, .2), legend="brief", label="Train CI")
sns.lineplot(base_perf_cox,x="nb_variables", y="CI_test", color=(0, 1, 0, 1), dashes=(2,2), legend="brief", label="Test CI")
sns.lineplot(aug_perf_cox,x="nb_variables", y="CI_test", color=(0, 1, 0, 1), legend="brief", label="Test CI")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")


plt.subplot(3,3,5)
plt.title("RSF (10 classifiers)")
plt.ylim(.5,1.2)
sns.lineplot(base_perf_rsf10,x="nb_variables", y="CI_train", color=(0, 1, 1, .2), dashes=(2,2), legend="brief", label="Train CI (RSF_10, Base)")
sns.lineplot(aug_perf_rsf10,x="nb_variables", y="CI_train", color=(0, 1, 1, .2), legend="brief", label="Train CI (RSF_10, Augmented)")
sns.lineplot(base_perf_rsf10,x="nb_variables", y="CI_test", color=(0, 1, 1, 1), dashes=(2,2), legend="brief", label="Test CI (RSF_10, Base)")
sns.lineplot(aug_perf_rsf10,x="nb_variables", y="CI_test", color=(0, 1, 1, 1), legend="brief", label="Test CI (RSF_10, Augmented)")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,6)
plt.title("RSF (100 classifiers)")
plt.ylim(.5,1.2)
sns.lineplot(base_perf_rsf100,x="nb_variables", y="CI_train", color=(0, .5, 1, .2), dashes=(2,2), legend="brief", label="Train CI (RSF_100, Base)")
sns.lineplot(aug_perf_rsf100,x="nb_variables", y="CI_train", color=(0, .5, 1, .2), legend="brief", label="Train CI (RSF_100, Augmented)")
sns.lineplot(base_perf_rsf100,x="nb_variables", y="CI_test", color=(0, .5, 1, 1), dashes=(2,2), legend="brief", label="Test CI (RSF_100, Base)")
sns.lineplot(aug_perf_rsf100,x="nb_variables", y="CI_test", color=(0, .5, 1, 1), legend="brief", label="Test CI (RSF_100, Augmented)")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,7)
plt.title("GB (10 classifiers)")
plt.ylim(.5,1.2)
sns.lineplot(base_perf_gb10,x="nb_variables", y="CI_train", color=(1, .5, 0, .2), dashes=(2,2), legend="brief", label="Train CI (GB_10, Base)")
sns.lineplot(aug_perf_gb10,x="nb_variables", y="CI_train", color=(1, .5, 0, .2), legend="brief", label="Train CI (GB_10, Augmented)")
sns.lineplot(base_perf_gb10,x="nb_variables", y="CI_test", color=(1, .5, 0, 1), dashes=(2,2), legend="brief", label="Test CI (GB_10, Base)")
sns.lineplot(aug_perf_gb10,x="nb_variables", y="CI_test", color=(1, .5, 0, 1), legend="brief", label="Test CI (GB_10, Augmented)")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")

plt.subplot(3,3,8)
plt.title("GB (100 classifiers)")
plt.ylim(.5,1.2)
sns.lineplot(base_perf_gb100,x="nb_variables", y="CI_train", color=(1, .5, 0, .2), dashes=(2,2), legend="brief", label="Train CI (GB_100, Base)")
sns.lineplot(aug_perf_gb100,x="nb_variables", y="CI_train", color=(1, .5, 0, .2), legend="brief", label="Train CI (GB_100, Augmented)")
sns.lineplot(base_perf_gb100,x="nb_variables", y="CI_test", color=(1, .5, 0, 1), dashes=(2,2), legend="brief", label="Test CI (GB_100, Base)")
sns.lineplot(aug_perf_gb100,x="nb_variables", y="CI_test", color=(1, .5, 0, 1), legend="brief", label="Test CI (GB_100, Augmented)")
plt.xlabel("Number of selected features")
plt.ylabel("Concordance Index")



plt.tight_layout()
plt.show()